name: Build and publish test package
on:
  pull_request:
    branches:
      - development
  workflow_dispatch:
    
jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov build twine

      - name: Test with pytest
        run: python -m pytest --cov --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml

      - name: Set test package version
        env:
          VERSION_SUFFIX: dev${{ github.run_number }}
        run: |
          cp pyproject.toml pyproject.toml.original
          sed -r "s/version = \"(.+)\"/version = \"\1-$VERSION_SUFFIX\"/" pyproject.toml.original > pyproject.toml 
          rm pyproject.toml.original

      - name: Build test package
        run: |
          python -m build
          python -m twine check dist/*
  
      - name: Publish test package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          verify_metadata: false
          repository_url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TESTPYPI_API_TOKEN}}
          