name: Test PyPI
on:
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install pytest build

      - name: Test with pytest
        run: |
          python -m pytest --cov --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml

      - name: Build package
        run: |
          python -m build
  